---
# Source: ray-cluster/templates/raycluster-cluster.yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
    app.kubernetes.io/name: kuberay
    helm.sh/chart: ray-cluster-1.0.0
    app.kubernetes.io/instance: raycluster
    app.kubernetes.io/managed-by: Helm
  name: raycluster-kuberay

spec:        
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
        dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-head
            image: rayproject/ray:latest-py310
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: "1"
                memory: 2G
              requests:
                cpu: "1"
                memory: 2G
        volumes:
          - emptyDir: {}
            name: log-volume
      metadata:
        labels: 
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-1.0.0
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm 
  workerGroupSpecs:
  - rayStartParams: {}
    replicas: 1
    minReplicas: 0
    maxReplicas: 2147483647
    groupName: workergroup
    template:
      spec:
        containers:
          - volumeMounts:
            - mountPath: /tmp/ray
              name: log-volume
            name: ray-worker
            image: rayproject/ray:latest-py310
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: "1"
                memory: 1G
              requests:
                cpu: "1"
                memory: 1G
        volumes:
          - emptyDir: {}
            name: log-volume
      metadata:
        labels: 
          app.kubernetes.io/name: kuberay
          helm.sh/chart: ray-cluster-1.0.0
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm
